name: Development Checks

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ develop, feature/*, bugfix/* ]

jobs:
  quality-check:
    name: Quality Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Analyze code
        run: flutter analyze
        
      - name: Run tests
        run: flutter test
        
      - name: Check formatting
        run: dart format --set-exit-if-changed .
        
      - name: Check for unused dependencies
        run: flutter pub deps --style=compact

  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    needs: quality-check
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build for Android (debug)
        run: flutter build apk --debug
        
      - name: Build for Web
        run: flutter build web 